"""Add artist table

Revision ID: 8f7a505eade3
Revises: 2414bf1eec84
Create Date: 2024-10-10 14:34:02.633665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7a505eade3'
down_revision = '2414bf1eec84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_song_artist', 'artist', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_constraint('fk_song_artist', type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
